### ISSUE TITLE
swagger 通过 $ref 循环引用如何解决？

### ISSUE THREAD

**Issue by yokochen222** [ldc2726/swagger-ts#1]
swagger json 地址 ： https://codepen.io/yokochen/pen/oNEMYpr

**Comment by ldc2726** [comment]
@yokochen222 Please describe your problem carefully

**Comment by ldc2726** [comment]
![image](https://user-images.githubusercontent.com/34648806/172047427-aeadfade-5faf-40b6-af9a-391e79e205bb.png)

We have just released the new version "1.2.0", which has solved all your problems. However, it must be pointed out that we have found many paths named in Chinese in your "Swagger", which are very non-standard and our system can not handle it, so we suggest modification.
